name: covefood_users
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.8
  country_picker: ^2.0.26
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_database: ^10.4.9
  firebase_messaging: ^14.7.19
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_geofire: ^2.0.3
  flutter_styled_toast: ^2.2.1
  font_awesome_flutter: ^10.7.0
  geolocator: ^11.1.0
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  http: ^1.2.0
  image_picker: ^1.0.8
  page_transition: ^2.1.0
  persistent_bottom_nav_bar: ^5.0.2
  persistent_bottom_nav_bar_v2: ^5.2.3
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  sizer: ^2.0.15
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/categories/
    - assets/images/splashScreenImage/
  fonts: 
    - family: UberMoveMedium
      fonts: 
        - asset: assets/fonts/UberMoveMedium.otf

    - family: UberMoveBold
      fonts: 
        - asset: assets/fonts/UberMoveBold.otf
